stages:
    # model_1_download:
    #     cmd:  python src/model_1/download/download.py
    #     deps:
    #         - src/model_1/download/download.py
    #     outs:
    #         - data/model_1/download/initial_data.csv
    #         - data/model_1/download/target.csv

  model_1_transform:
    cmd: python src/model_1/transform/transform.py
    deps:
        - data/model_1/download/raw_data.parquet
    outs:
        - data/model_1/transform/X_test.parquet
        - data/model_1/transform/X_train.parquet
        - data/model_1/transform/y_test.parquet
        - data/model_1/transform/y_train.parquet

  model_1_train:
    cmd: python src/model_1/train/train.py
    deps:
        - data/model_1/transform/X_test.parquet
        - data/model_1/transform/X_train.parquet
        - data/model_1/transform/y_test.parquet
        - data/model_1/transform/y_train.parquet
 
    outs:
        - data/model_1/params/params.yaml

